server:
  port: ${APP_PORT}

spring:
  application:
    name: msa4-lms-v2-scg
    version: v1
  web:
    error:
      include-stacktrace: always
      include-message: always
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - name: RequestSize
              args:
                maxSize: 20MB
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins: ${CORS_ALLOW_ORIGIN}
                allowed-methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
                allowed_headers: "*"
                allow-credentials: true
          routes:
            - id: ${AUTH_SERVICE_NAME}
              uri: ${AUTH_SERVICE_URI}
              predicates:
                - Path=${AUTH_SERVICE_PREDICATE}

            - id: ${ACADEMIC_SERVICE_NAME}
              uri: ${ACADEMIC_SERVICE_URI}
              predicates:
                - Path=${ACADEMIC_SERVICE_PREDICATE}

            - id: ${PAYMENT_SERVICE_NAME}
              uri: ${PAYMENT_SERVICE_URI}
              predicates:
                - Path=${PAYMENT_SERVICE_PREDICATE}

            # Open API UI가 각 하위 서비스의 스펙을 Gateway가 origin으로 받아와서 출력하도록 설정
            - id: ${AUTH_SERVICE_NAME}-docs
              uri: ${AUTH_SERVICE_URI}
              predicates:
                - Path=/${AUTH_SERVICE_NAME}${AUTH_SERVICE_OPEN_API_PATH}
              filters:
                - RewritePath=/${AUTH_SERVICE_NAME}${AUTH_SERVICE_OPEN_API_PATH}, ${AUTH_SERVICE_OPEN_API_PATH}

            - id: ${ACADEMIC_SERVICE_NAME}-docs
              uri: ${ACADEMIC_SERVICE_URI}
              predicates:
                - Path=/${ACADEMIC_SERVICE_NAME}${ACADEMIC_SERVICE_OPEN_API_PATH}
              filters:
                - RewritePath=/${ACADEMIC_SERVICE_NAME}${ACADEMIC_SERVICE_OPEN_API_PATH}, ${ACADEMIC_SERVICE_OPEN_API_PATH}

            - id: ${PAYMENT_SERVICE_NAME}-docs
              uri: ${PAYMENT_SERVICE_URI}
              predicates:
                - Path=/${PAYMENT_SERVICE_NAME}${PAYMENT_SERVICE_OPEN_API_PATH}
              filters:
                - RewritePath=/${PAYMENT_SERVICE_NAME}${PAYMENT_SERVICE_OPEN_API_PATH}, ${PAYMENT_SERVICE_OPEN_API_PATH}


# Open API (Swagger)
springdoc:
  swagger-ui:
    path: /docs
    urls:
      - name: ${AUTH_SERVICE_NAME}
        url: /${AUTH_SERVICE_NAME}${AUTH_SERVICE_OPEN_API_PATH}

      - name: ${ACADEMIC_SERVICE_NAME}
        url: /${ACADEMIC_SERVICE_NAME}${ACADEMIC_SERVICE_OPEN_API_PATH}

      - name: ${PAYMENT_SERVICE_NAME}
        url: /${PAYMENT_SERVICE_NAME}${PAYMENT_SERVICE_OPEN_API_PATH}


# jwt
jwt:
  header-key: Authorization
  scheme: Bearer
  secret: ${JWT_SECRET}
  public-paths:
    - /api/auth/student/login
    - /api/auth/professor/login
    - /api/auth/admin/login
    - /api/auth/reissue-token
    - /docs
    - /docs/**
    - /swagger-ui/**
    - /webjars/**
    - /*/api-docs
    - /*/api-docs/**
